// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    AuthLayout: typeof import('./../src/components/auth/AuthLayout.vue')['default']
    BestProject: typeof import('./../src/components/home/BestProject.vue')['default']
    BlockSession: typeof import('./../src/components/includes/BlockSession.vue')['default']
    IAntDesignLikeFilled: typeof import('~icons/ant-design/like-filled')['default']
    IBiInfoCircleFill: typeof import('~icons/bi/info-circle-fill')['default']
    IBxBxsCategoryAlt: typeof import('~icons/bx/bxs-category-alt')['default']
    IIcSharpCloudUpload: typeof import('~icons/ic/sharp-cloud-upload')['default']
    IIcSharpSettings: typeof import('~icons/ic/sharp-settings')['default']
    IIonChatbubbleEllipses: typeof import('~icons/ion/chatbubble-ellipses')['default']
    IIonHeart: typeof import('~icons/ion/heart')['default']
    IMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IMaterialSymbolsArrowForwardRounded: typeof import('~icons/material-symbols/arrow-forward-rounded')['default']
    IMaterialSymbolsBookmarkAddRounded: typeof import('~icons/material-symbols/bookmark-add-rounded')['default']
    IMaterialSymbolsShare: typeof import('~icons/material-symbols/share')['default']
    IMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IMdiPencilCircle: typeof import('~icons/mdi/pencil-circle')['default']
    IRiCompass3Fill: typeof import('~icons/ri/compass3-fill')['default']
    MasterLayout: typeof import('./../src/components/includes/MasterLayout.vue')['default']
    OnBoard: typeof import('./../src/components/home/OnBoard.vue')['default']
    ProjectItem: typeof import('./../src/components/includes/ProjectItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowCase: typeof import('./../src/components/home/ShowCase.vue')['default']
    SiteHeader: typeof import('./../src/components/includes/SiteHeader.vue')['default']
    SubMenu: typeof import('./../src/components/includes/SubMenu.vue')['default']
    WhyUs: typeof import('./../src/components/home/WhyUs.vue')['default']
  }
}
